# Generated by Django 3.0.7 on 2020-06-14 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0003_auto_20200614_2147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='description',
            field=models.CharField(default='', max_length=60),
        ),
        migrations.AlterField(
            model_name='city',
            name='icon',
            field=models.CharField(default='', max_length=25),
        ),
    ]
