# Generated by Django 3.0.7 on 2020-06-14 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0007_auto_20200614_2155'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='description',
        ),
        migrations.RemoveField(
            model_name='city',
            name='icon',
        ),
        migrations.RemoveField(
            model_name='city',
            name='temperature',
        ),
    ]
