# Generated by Django 3.0.7 on 2020-06-16 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0008_auto_20200614_2219'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='description',
            field=models.CharField(default='', max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='city',
            name='icon',
            field=models.CharField(default='', max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='city',
            name='temperature',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=4, null=True),
        ),
    ]
